### ISSUE TITLE
Write a Blog post about the Little Red School House and the Powerhouse Museum

### ISSUE THREAD

**Issue by 32bpwr3** [ShepherdMapleSyrupFestivalMi/SMSF2019#19]
Reach out to Joyce and Larry Noyes and ask them questions about the history behind the museums, and what visitors can expect to see.

**Comment by Jpmtpleasant** [comment]
Here is something about the Little Red School House and Museum.

https://docs.google.com/document/d/131_WdNEn2CWk82ci12yHrTwjEYITnzWE7kkAo7EGJwQ/edit?usp=sharing

**Comment by 32bpwr3** [comment]
Great, I am looking for two blog posts which focus on each of the museum. Include the days/times that the museum will be open, and include quotes from Joyce and Larry.
