### ISSUE TITLE
Create a Media Release form for the Shepherd Maple Syrup Festival

### ISSUE THREAD

**Issue by 32bpwr3** [ShepherdMapleSyrupFestivalMi/SMSF2019#29]
Adapt the following form into a form that the SMSF can distribute to volunteers, and parents. Will be used for the contestants in the Princess Pageant.

https://www.pdffiller.com/36022902-fillable-media-release-form-for-schools-slps

Compose the form in Google Docs and post a link to the completed document in this issue for review.

**Comment by JPsmsfgaragesaleadmin** [comment]
I'll take this assignment

**Comment by Jpmtpleasant** [comment]
Completed document
https://docs.google.com/document/d/1fO3Y0IB4uxw24znku4jVxNGQBjH2frsZlXUC4rB30-I/edit?usp=sharing

**Comment by 32bpwr3** [comment]
This looks good.
