### ISSUE TITLE
Leave Behind

### ISSUE THREAD

**Issue by 32bpwr3** [ShepherdMapleSyrupFestivalMi/SMSF2019#30]
The plan is to produce a half-sheet "leave behind" card that can be dropped off at rest stops and visitor centers around the state. It would highlight the major festival events.

**Comment by Jpmtpleasant** [comment]
https://drive.google.com/file/d/1EaVRJfpYUF_9nI4Fw-R7YDNMFzD0cYE-/view?usp=sharing

**Comment by 32bpwr3** [comment]
Thanks, I"ll take a look.

**Comment by 32bpwr3** [comment]
@JuliaSech keep working with Patti on the leave-behind. Feel free to reference the design from @Jpmtpleasant . Thanks.
