### ISSUE TITLE
Create a QR Code that can be added to the SMSF Flyer

### ISSUE THREAD

**Issue by 32bpwr3** [ShepherdMapleSyrupFestivalMi/SMSF2019#33]
Create a small-to-medium sized QR code which can be incorporated into the design of this year's SMSF flyer. Would go on the outside panel.

The QR Code would point to the website.

**Comment by Jpmtpleasant** [comment]
Do you want it to direct to the website or the Facebook page?

**Comment by 32bpwr3** [comment]
Thanks, this looks good.
